### ISSUE TITLE
使用方式

### ISSUE THREAD

**Issue by transtone** [miaolz123/vue-markdown#1]
```<vue-markdown source="..."></vue-markdown>```
文档里通常这样来用，可否这样用：

```<vue-markdown> ... </vue-markdown>```

========= 好吧，搞错了。

**Comment by miaolz123** [comment]
多谢反馈哦，这个功能已经实现 ~ [Slots](https://github.com/miaolz123/vue-markdown#slots)

欢迎多提需求哦

**Comment by transtone** [comment]
我后来是用 webpack 的 markdown loader 处理的 .md 文件，import 到 组件里，再通过 v-html 放到想要的地方。
想实现的是 ant.design 中文档的写法，将 md 文件混在 template 当中。（现在他们又改了一种做法）

回头试试这个方案：）

移动端的富文本编辑器功能其实也可以基于本组件实现，很多需求正在路上...
