### ISSUE TITLE
.webp images don't work in iOS

### ISSUE THREAD

**Issue by starkey-aegis** [miaolz123/vue-markdown#114]
Take the following markdown
`![image](https://i.giphy.com/media/NTur7XlVDUdqM/giphy.webp)`

This does not work on iOS browsers.  According to [this](https://news.ycombinator.com/item?id=20639439)

> you can use the `<picture>` element to show webP images and fallback to PNGs for browsers that don’t support webP

**Comment by YanDevDe** [comment]
You can't use .webp at all in iOS devices. Safari Webkit doesn't allow that.
