### ISSUE TITLE
Import external markdown

### ISSUE THREAD

**Issue by guillaumemolter** [miaolz123/vue-markdown#16]
I'm a JS and Vue.js noob so forgive me if this a dumb question.

Is there a way to parse and render markdown text from a .md file stored in my static folder? Maybe using `import` or `webpack`?

If yes I think documenting this would be a great addition :-)

**Comment by miaolz123** [comment]
I am sorry to answer you, it can not be used like this because it can only parse the string ~

**Comment by miaolz123** [comment]
However, there is an idea, you can read the contents of the file into a string and then use this tool.

Hope this can help you!

**Comment by guillaumemolter** [comment]
Thanks for your response!

Yes found this : https://github.com/webpack/raw-loader that should work

**Comment by miaolz123** [comment]
Awesome!
