### ISSUE TITLE
question of plug-ins

### ISSUE THREAD

**Issue by linzhipeng** [miaolz123/vue-markdown#17]
(I'm sorry for my poor English)
I use webpack to build my project.
When I use the vue-markdown, It compiled with 2 warnings.
Usually it always has warning because of the case sensitive with the plugin's name.
Can you see the problem?
![default](https://cloud.githubusercontent.com/assets/11245015/22813305/a5983c64-ef85-11e6-9cda-d6036c2413d8.PNG)

**Comment by miaolz123** [comment]
看起来应该是你装了两遍buffer，一个是全局的，一个是本项目内部的，建议删除一个即可，也就是两个文件夹删除一个。
