### ISSUE TITLE
怎么使用块渲染

### ISSUE THREAD

**Issue by janchengwang** [miaolz123/vue-markdown#19]
`<vue-markdown>
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
 		### 你好
    </vue-markdown>`

这样子渲染不出来

**Comment by miaolz123** [comment]
你好，上面的代码看起来是没有问题的，这边有一个简单的例子你可以参考已下。

https://github.com/miaolz123/vue-markdown/blob/master/example/simple/index.html
