### ISSUE TITLE
Using Multi-line Content, Using Basic Markdown Syntax

### ISSUE THREAD

**Issue by philmaker1** [miaolz123/vue-markdown#2]
Vue-markdown does not seem to render properly with multi-line markdown unless I append &nbsp; for example immediately after the opening tag. Basic markdown syntax such as headers and lists do not appear to render.

**Comment by miaolz123** [comment]
Sorry to comment too late!!!

Maybe i don't get your point clearly, can you post the example script on this occasion?

Thx~
