### ISSUE TITLE
换行符\n好像没有用

### ISSUE THREAD

**Issue by SidKwok** [miaolz123/vue-markdown#3]
在官方的示例里面输入\n就没有用，尽管breaks为true。

**Comment by SidKwok** [comment]
噢 我突然发现了使用slot模式的话\n是没有用的，但是用source就可以。

**Comment by miaolz123** [comment]
内个，Markdown和HTML里面的话你试试下面这个用`<br>`

**Comment by SidKwok** [comment]
噢噢，其实问题不大，直接用source也可以解决。很厉害的项目，赞一个✌️
