### ISSUE TITLE
Putting a class on a markdown heading

### ISSUE THREAD

**Issue by kaydwithers** [miaolz123/vue-markdown#31]
I'm building a site with Contentful and I'm trying to put a class on a heading. 

My code looks like the below
```
<vue-markdown class="f3">
  ### {{ hello.fields.heading }}
</vue-markdown>
```

And renders out to
```
<div class="f3">
  <h3>Hello</h3>
</div>
```

What I would really like to render out is
```
<h3 class="f3">
  Hello
</h3>
```

Is **putting a class on a markdown heading** possible? Sorry if this has been covered already.

**Comment by miaolz123** [comment]
Is looks like is impossible to achieve, but you can write HTML in markdown string like this:

``` markdown
<h3 class="f3">Hello</h3>
```

I'm very sorry because this is not a good idea.
