### ISSUE TITLE
How to use external .md file?

### ISSUE THREAD

**Issue by thearabbit** [miaolz123/vue-markdown#52]
I base on `Meteor + Vue`.
```js
// changelog.md
# Vue markdown
...........
----------
<template>
   <vue-markdown source="./changelog.md"></vue-markdown>
</template>
```
But don't work, please help me

**Comment by goldenram** [comment]
Yes, I expected source="filename" to work, but it appears the string is just a text string.  I am guessing we have to use axios or some other file loader to do a file load into a string, then pass that into the source attribute.

**Comment by goldenram** [comment]
Here is quick component I came up with wrap this one:

```
<template>
    <vue-markdown :source="mdText"></vue-markdown>
</template>

<script>
import axios from 'axios'

export default
{
    name: 'md-viewer',
    props: ["src"],
    data: function()
    {
        return ({"mdText": ""});
    },
    mounted()
    {
        axios.get(this.src).then(response => {this.mdText = response.data})
    }
}
</script>

<style lang="scss"></style>
```

Then import and call it:

 `<md-viewer src="file.md"></md-viewer>`

**Comment by thearabbit** [comment]
Thanks for your reply.
But don't understand
```
<md-viewer src="file.md"></md-viewer>
```

**Comment by thearabbit** [comment]
Now it works fine.
