### ISSUE TITLE
server side rendering?

### ISSUE THREAD

**Issue by devCrossNet** [miaolz123/vue-markdown#57]
Hey, I just added `vue-markdown` to my project.
It's an isomorphic app that needs to be SEO optimized and this component seems to not render on the server.

Is it possible somehow already or does it have to be implemented?

Regards

**Comment by benjick** [comment]
Did you solve it?

**Comment by devCrossNet** [comment]
@benjick I created my own component with SSR support, it was easier than I thought: https://github.com/vuesion/vuesion/tree/master/src/app/shared/components/VueMarkdown
