### ISSUE TITLE
能否支持特殊字符包围的文本原样输出？

### ISSUE THREAD

**Issue by wukaikailive** [miaolz123/vue-markdown#7]
我遇到的问题是这样的，我需要支持laTex公式，先用vue-markdown渲染一次后，再用mathjax渲染一次。书写LaTex公式时，需要被$或者$$包围起来，使用vue-markdown渲染后会在原来的公式前后包围一个p标签，导致mathjax无法正确解析LaTex公式，有什么办法可以解决这个问题吗？或者说通过某些配置，让vue-markdown不处理$或者$$包围的文本？

**Comment by brianbancroft** [comment]
Hi there, I can't read or speak Chinese, but it appears that mathjax is wanted as an enhancement? 

I'd love to attempt to contribute. I've found this library called [`markdown-it-mathjax`](https://github.com/classeur/markdown-it-mathjax). It appears to be similar in structure in the setup to [`markdown-it-emoji`](https://github.com/markdown-it/markdown-it-emoji), which you use in this library. 

I haven't contributed to open source in any serious way, so this might flop. I'm still going to give it a go. I'll let you know how it goes here.

**Comment by Aleksey-Danchin** [comment]
https://github.com/brianbancroft/vue-markdown has 404 status
