### ISSUE TITLE
Bundle Size Reduction

### ISSUE THREAD

**Issue by brophdawg11** [miaolz123/vue-markdown#77]
Is there any way to opt in to portions of the `vue-markdown` package for limited functionality and a smaller build?  The bundle is prohibitively large for a simple markdown display component.

https://bundlephobia.com/result?p=vue-markdown@2.2.4

**Comment by failpunk** [comment]
Anyone using any alternatives? There haven't been any commits in well over a year and this this is huge!

**Comment by wopian** [comment]
The only other alternatives I'm aware of are considerably larger than `vue-markdown`'s 167.7 kB size 😭

203.7 kB https://bundlephobia.com/result?p=vue-simple-markdown@1.0.8
232.9 kB https://bundlephobia.com/result?p=m-markdown-preview@1.0.0
1.1 mB https://bundlephobia.com/result?p=markdown-it-vue@1.0.5

**Comment by BlakeCampbells** [comment]
I just went through and used [marked](https://github.com/markedjs/marked)

What I came up with was alot like [Basic Examples](https://vuejs.org/v2/examples/)

Just as a way to keep refactoring easy I name this 
## vue-markdown
```
<template>
  <div v-html="compiledMarkdown"></div>
</template>

<script>
import marked from 'marked'

export default {
  props: {
    source: { default: '', type: String },
  },
  computed: {
    compiledMarkdown: function () {
      if(this.source){
        return marked(this.source, { sanitize: true, breaks: true })
      }
    }
  },
}
</script>
```

Then my components were changed from 
### Before
```
<vue-markdown :html="true" :linkify="true" :source="webContent"/>
```

### After
```
<vue-markdown :source="webContent"/>
```

After changing the imports to look at my component it was good. If you are using VueMarkdown's more advanced options then you might need to make additional changes.
