### ISSUE TITLE
是否缺少了 css 文件

### ISSUE THREAD

**Issue by Teddy-Zhu** [miaolz123/vue-markdown#8]
使用后没有样式

**Comment by miaolz123** [comment]
@Teddy-Zhu 确实是没有样式的哦，该插件只负责把`markdown`转换成`html`，具体的css要自己引入的，喜欢哪个引入哪个就行了。

比如[这个例子](http://miaolz123.github.io/vue-markdown/)就是在[main.css](http://miaolz123.github.io/vue-markdown/dist/css/main.css)里面引入了`Bootstrap v3.3.6`才显示这个样式的。

你可以在网页头部添加下面一行就行：
``` html
<link rel="stylesheet" href="http://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css">
```

不知道是否解决了你的疑问？

**Comment by Teddy-Zhu** [comment]
好吧, 明白了
其实样式是最难找的, 我试了不同的markdown渲染的工具, 渲染出来的html各不相同, css也不同,所以想找个最匹配的...
